### ISSUE TITLE
No way to add / remove / view trackers

### ISSUE THREAD

**Issue by djgamerr** [latop2604/UTorrentClientApi#11]
Hello,
I have been trying your library for a day or two, and it is really nice, but:
i cant seem to find a way to pull tracker list of a given torrent, is that even possible?

Sincerely.

**Comment by latop2604** [comment]
This feature is not implemented. You can find uTorrent api description here http://help.utorrent.com/customer/en/portal/articles/1573951-torrent-job-properties---webapi

**Comment by djgamerr** [comment]
Thanks for the headsup
will try to implement that, and post bask code changes.

**Comment by djgamerr** [comment]
[https://www.dropbox.com/s/rs5av2tp8wfcfll/UTorrentClientApi-master.rar?dl=1](url)

Here you go, i changed 2 things:
1) added a way to read props (GetProps under result)
2) fixed a way you handle/force urls, so you wont have "http://https://", so now it works under https proxy as well

Feel free to post a commit for everyone to use.

**Comment by latop2604** [comment]
Hello, thx for your work.

Can you create a proper pull request ?

**Comment by djgamerr** [comment]
Done :)

**Comment by latop2604** [comment]
I let this issue open until Add/Remove features are added
