### ISSUE TITLE
post torrent issue

### ISSUE THREAD

**Issue by tmathura** [latop2604/UTorrentClientApi#9]
When posting a torrent use the UTorrentClientApi, if you set the path, it does not seed, it seems that uTorrent appends the default download location to the path that you specified.

**Comment by latop2604** [comment]
Yes, this is how utorrent api is working. If you want to use a totaly different path, you need to set it through [settings api ](https://github.com/latop2604/UTorrentClientApi/blob/master/UTorrentClientApi/UTorrentClient.cs#L704)

**Comment by tmathura** [comment]
But using the settings API would mean I am changing the global download path setting, correct?

**Comment by latop2604** [comment]
Yes

**Comment by latop2604** [comment]
You can restore previous setting value after uploading

**Comment by tmathura** [comment]
Cool. I will give that a try and see how far I come. Thanks.

**Comment by tmathura** [comment]
> Yes, this is how utorrent api is working. If you want to use a totaly different path, you need to set it through [settings api ](https://github.com/latop2604/UTorrentClientApi/blob/master/UTorrentClientApi/UTorrentClient.cs#L704)

This solution worked :-) thank you
